layout_spectrum: 1
typography_spectrum: 0.7883642
color:
  saturation: 0.2004887
  lightness: 0.845609
  brandStrength: 0.5354131
  brandColors:
    - '#DFAB01'
    - '#CDCFC5'
    - '#0B0B0F'
    - '#879288'
    - '#D8CD53'
  rhythmicContrast: 0.01825258
name: N-finity Test
